#!/usr/bin/env bash

# CONFIGURACIÓN DEL SISTEMA DE PUNTOS - XGEREMY™
# Guía paso a paso para conectar con Google Sheets

echo "═══════════════════════════════════════════════════════════════"
echo "  SISTEMA DE FIDELIZACIÓN DE PUNTOS - XGEREMY™"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Este archivo de configuración te guiará para conectar el sistema"
echo "de puntos con tu Google Sheet."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 1: CREAR GOOGLE CLOUD PROJECT"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Visita: https://console.cloud.google.com/"
echo "2. Crea un nuevo proyecto (nombre: 'XGEREMY-Puntos')"
echo "3. Selecciona el proyecto"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 2: HABILITAR GOOGLE SHEETS API"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ve a: APIs & Services > Library"
echo "2. Busca: 'Google Sheets API'"
echo "3. Haz click en 'Enable'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 3: CREAR CREDENCIALES (API KEY)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ve a: APIs & Services > Credentials"
echo "2. Haz click en: 'Create Credentials' > 'API Key'"
echo "3. Copia la API Key (la necesitarás en el siguiente paso)"
echo ""
echo "⚠️  SEGURIDAD: Considera usar service account y restringir el acceso"
echo "    por referrer a tu dominio: https://xgeremy.github.io"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 4: CREAR TU GOOGLE SHEET"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ve a: https://sheets.google.com"
echo "2. Crea una nueva hoja de cálculo"
echo "3. Renombra la hoja a: 'Cliente'"
echo ""
echo "ESTRUCTURA DE COLUMNAS (en A1:F1):"
echo "┌─────────────────────────────────────────┐"
echo "│ A        │ B        │ C      │ D    │ E │ F         │"
echo "├──────────┼──────────┼────────┼──────┼──┼──────────┤"
echo "│ Nombre   │ Email    │ Puntos │ Tier │  │ Monto    │"
echo "│ (texto)  │ (texto)  │ (num)  │ (txt)│  │ CLP (num)│"
echo "└─────────────────────────────────────────┘"
echo ""
echo "EJEMPLO DE DATOS (fila 2 en adelante):"
echo "Geremy Mora | geremy@example.com | 145 | Gold | 15/02/2026 | 250000"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 5: OBTENER ID DEL SHEET"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre tu Google Sheet"
echo "2. En la URL verás algo como:"
echo "   https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID/edit"
echo "3. Copia la parte YOUR_SHEET_ID"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 6: ACTUALIZAR app.js"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Abre: /puntos/app.js"
echo "2. Busca las líneas:"
echo ""
echo "   const GOOGLE_SHEETS_API_URL = 'https://sheets.googleapis.com/v4/spreadsheets';"
echo "   const SHEET_ID = 'YOUR_SHEET_ID';"
echo "   const API_KEY = 'YOUR_API_KEY';"
echo ""
echo "3. Reemplaza:"
echo "   - YOUR_SHEET_ID con el ID de tu sheet"
echo "   - YOUR_API_KEY con tu API Key"
echo ""
echo "EJEMPLO:"
echo "   const SHEET_ID = '1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p';"
echo "   const API_KEY = 'AIzaSyDx..."
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASO 7: COMPARTIR GOOGLE SHEET"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Si usas API Key: El sheet debe ser 'Visible para quien tenga link'"
echo "2. Si usas Service Account: Comparte el sheet con el email de la cuenta"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ACTUALIZAR PUNTOS MANUALMENTE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Tú actualizas el Google Sheet manualmente:"
echo ""
echo "1. Abre tu Google Sheet"
echo "2. Modifica los valores en la columna 'Puntos' (C)"
echo "3. El dashboard se sincroniza automáticamente cada 30 segundos"
echo ""
echo "CÁLCULO DE PUNTOS:"
echo "- 1 punto = 1000 CLP de crédito"
echo "- 150 puntos = Sesión de día completo (valuada en 180k, precio real 120k)"
echo "- Cliente gasta 150k CLP → gana 15 puntos"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "BONUS POINTS (VERIFICACIÓN MANUAL)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Agrega estos puntos manualmente en el sheet:"
echo "- Seguir TikTok: +1 punto"
echo "- Seguir Instagram: +1 punto"
echo "- 2 tatuajes en 1 mes: +5 puntos"
echo ""
echo "El cliente contacta por TikTok/Instagram y tú verificas y actualizas"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TIERS AUTOMÁTICOS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "El sistema calcula automáticamente el tier:"
echo "- Bronze: 0-50 puntos"
echo "- Silver: 51-100 puntos"
echo "- Gold: 101-150 puntos"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TEST"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ve a: https://xgeremy.github.io/puntos/"
echo "2. Ingresa un email"
echo "3. Deberías ver tus datos del Google Sheet"
echo ""
echo "Si no funciona, revisa la consola del navegador (F12 > Console)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "SOPORTE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Errores comunes:"
echo ""
echo "1. 'API not found':"
echo "   → Verifica que habilitaste Google Sheets API"
echo "   → Espera 2-3 minutos después de habilitar"
echo ""
echo "2. 'Unauthorized':"
echo "   → Verifica que tu API Key sea correcta"
echo "   → Asegúrate de que el sheet sea accesible públicamente"
echo ""
echo "3. 'Not found':"
echo "   → Verifica que el SHEET_ID sea correcto"
echo "   → El sheet debe tener una hoja llamada 'Cliente'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Cuando todo esté configurado, el dashboard funcionará perfectamente"
echo ""
